"""Frozen-source normal controls. Fake providers; not live host/Agent evidence.

Unittest writes only temporary evidence. --evidence-dir archives into a new
directory, refusing overwrite. Each version imports the SAME existing fixture
in its own process, with a different source root.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import traceback
import unittest

ROOT = Path(__file__).resolve().parents[1]
VERSIONS = {
    "old": "fcd28a4b93f7d63df6b3e0445ea538e48e51c8c3",
    "candidate": "5a2d951a50cea246d52cbc827e0ef63c0053fd7e",
}
MODULES = ("agent-runtime.py", "prediction_feedback.py", "impact_prediction.py")


def write_json(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def require(condition, description):
    if not condition:
        raise AssertionError(description)


def save_process(directory, name, result):
    (directory / f"{name}.stdout").write_text(result.stdout, encoding="utf-8")
    (directory / f"{name}.stderr").write_text(result.stderr, encoding="utf-8")
    write_json(directory / f"{name}.command.json", {"argv": result.args, "returncode": result.returncode})


def run_worker(source, output, missing_fact=False):
    os.environ["SULDE_R3_SOURCE_ROOT"] = str(source)
    sys.path.insert(0, str(ROOT / "tests"))
    import test_r3_real_entry_chain as fixture

    for module in (fixture.ip, fixture.pf):
        require(Path(module.__file__).resolve().parent == source / "scripts/kb", "wrong source import")
    runtime = fixture.load_runtime_module()
    require(Path(runtime.__file__).resolve() == source / "scripts/kb/agent-runtime.py", "wrong runtime")
    identities = {name: {"path": str(source / "scripts/kb" / name),
                         "sha256": digest(source / "scripts/kb" / name)} for name in MODULES}
    write_json(output / "source-identities.json", identities)
    outcomes = {}
    for mode in ("wellbehaved", "markerdriven"):
        evidence = output / mode
        evidence.mkdir()
        with tempfile.TemporaryDirectory(prefix="sulde-normal-control-") as tmp:
            chain = fixture._Chain(Path(tmp), mode=mode)
            chain.seed_prediction()
            artifact = chain.state / f"prediction-feedback-{fixture.ip.digest('embed')}.json"
            try:
                if mode == "markerdriven":
                    first = chain.run()
                    save_process(evidence, "prepare", first)
                    require(first.returncode != 0, "preparation must be retryable failure")
                    require(artifact.is_file(), "no feedback generated by actual run")
                    pending = json.loads(artifact.read_text(encoding="utf-8"))
                    write_json(evidence / "pending-before-send.json", pending)
                    (evidence / "prepare.stdin").write_text(chain.captured_prompt(), encoding="utf-8")
                    require(pending["task_id_sha256"] == fixture.ip.digest("embed"), "wrong task")
                    request = pending["request_id"]
                    require(bool(request) and bool(pending["run_id_sha256"]), "missing source identity")
                    result = chain.run(retry_op="normal-pair-retry")
                else:
                    result = chain.run()
                save_process(evidence, "run", result)
                require(result.returncode == 0, result.stdout + result.stderr)
                status_text = (chain.state / "embed.status").read_text(encoding="utf-8")
                require(status_text.startswith("status=success rc=0 "), "managed task did not succeed")
                status = json.loads((chain.state / "embed.guardian.json").read_text(encoding="utf-8"))
                events = [row for path in sorted(chain.state.glob("*.run.jsonl"))
                          for row in map(json.loads, path.read_text(encoding="utf-8").splitlines()) if row]
                feedback = [e for e in events if e.get("type") == "prediction.feedback"]
                expected = (["as_predicted"] if mode == "wellbehaved"
                            else ["larger_than_predicted", "as_predicted"])
                require([e["payload"]["verdict"] for e in feedback] == expected, "verdict chain differs")
                require(all(e["payload"]["status"] == "checked" for e in feedback), "prediction skipped")
                prompt = chain.captured_prompt()
                (evidence / "run.stdin").write_text(prompt, encoding="utf-8")
                require(not artifact.exists(), "pending artifact remains")
                if mode == "wellbehaved":
                    require(fixture.FEEDBACK_MARKER not in prompt, "unexpected feedback")
                    require(not (chain.state / "prediction-feedback-consumed.json").exists(), "unexpected registry")
                else:
                    require(fixture.FEEDBACK_MARKER in prompt, "feedback absent from stdin")
                    require(pending["verdict"] in prompt, "verdict absent from stdin")
                    require(all(fact in prompt for fact in pending["facts"]), "facts absent from stdin")
                    registry = json.loads((chain.state / "prediction-feedback-consumed.json").read_text(encoding="utf-8"))
                    # Negative control removes an observed fact IN MEMORY ONLY.
                    if missing_fact:
                        registry["consumed"].pop(request)
                    require(request in registry["consumed"], "missing exact consumption fact")
                    consumed = registry["consumed"][request]
                    run_id = status["execution"]["run_id"]
                    require(consumed["consuming_run_id_sha256"] == fixture.ip.digest(run_id), "wrong consuming run")
                    require(consumed["consuming_run_id_sha256"] != pending["run_id_sha256"], "self consumption")
                    contract = json.loads((chain.state / "embed.intent.json").read_text(encoding="utf-8"))
                    require(consumed["consuming_session_id_sha256"] == fixture.ip.digest("managed:" + contract["intent_id"]), "wrong consuming session")
                    delivery = [e for e in events if e.get("type") == "prediction.feedback_consumed"
                                and e.get("run_id") == run_id]
                    require(len(delivery) == 1, "missing/duplicate delivery event")
                    require(delivery[0]["payload"]["request_id"] == request, "wrong delivered request")
                    require(delivery[0]["payload"]["prediction_id"] == pending["prediction_id"], "wrong delivered prediction")
                    require(not delivery[0]["payload"].get("send_failed"), "stdin send failed")
                probe = chain.probe()
                save_process(evidence, "probe", probe)
                require(probe.returncode == 0 and probe.stdout.strip() == "ok 2", "independent probe failed")
                outcomes[mode] = {"passed": True, "run_id": status["execution"]["run_id"], "verdicts": expected}
            finally:
                shutil.copytree(chain.state, evidence / "state", symlinks=True)
                for name in ("value.py", "consumer.py"):
                    shutil.copyfile(chain.worktree / name, evidence / name)
    require(all(digest(source / "scripts/kb" / name) == data["sha256"]
                for name, data in identities.items()), "tested source mutated")
    require(not list(source.rglob("*.pyc")), "source polluted with bytecode")
    write_json(output / "worker-result.json", {"passed": True, "cases": outcomes})


def run_pair(output, *, missing_fact=False):
    output.mkdir(parents=True, exist_ok=False)
    shutil.copyfile(__file__, output / "test_r3_normal_pair.py")
    shutil.copyfile(ROOT / "tests/test_r3_real_entry_chain.py", output / "test_r3_real_entry_chain.py")
    results = {}
    for label, commit in VERSIONS.items():
        evidence = output / label
        evidence.mkdir()
        with tempfile.TemporaryDirectory(prefix=f"sulde-pair-{label}-") as tmp:
            source = Path(tmp) / "source"
            source.mkdir()
            archive = subprocess.run(["git", "-C", str(ROOT), "archive", commit], capture_output=True, check=True)
            subprocess.run(["tar", "-x", "-C", str(source)], input=archive.stdout, check=True)
            isolated_home = Path(tmp) / "home"
            isolated_home.mkdir()
            env = {k: v for k, v in os.environ.items()
                   if not k.startswith(("SULDE_", "CODEX_", "CLAUDE_", "PYTHON"))}
            env.update({"PYTHONDONTWRITEBYTECODE": "1", "SULDE_HOME": str(isolated_home),
                        "SULDE_KB_DATA_ROOT": str(isolated_home / "data/kb")})
            command = [sys.executable, "-B", str(Path(__file__).resolve()),
                       "--worker", str(source), "--output", str(evidence)]
            if missing_fact:
                command.append("--missing-fact")
            completed = subprocess.run(command, env=env, capture_output=True, text=True,
                                       encoding="utf-8", errors="replace", timeout=120)
            save_process(evidence, "worker", completed)
            receipt = evidence / "worker-result.json"
            passed = (completed.returncode == 0 and receipt.is_file()
                      and json.loads(receipt.read_text(encoding="utf-8")).get("passed") is True)
            results[label] = {"commit": commit, "returncode": completed.returncode, "passed": passed}
    passed = all(item["passed"] for item in results.values())
    write_json(output / "summary.json", {
        "schema": "sulde-normal-pair-evidence-v1", "passed": passed,
        "versions": results, "negative_control": missing_fact,
        "driver_sha256": digest(Path(__file__)),
        "fixture_sha256": digest(ROOT / "tests/test_r3_real_entry_chain.py"),
        "python": sys.version, "scope": "fake-provider protocol, not live host authority",
    })
    manifest = "".join(f"{digest(p)}  {p.relative_to(output).as_posix()}\n"
                       for p in sorted(output.rglob("*")) if p.is_file() and not p.is_symlink())
    (output / "sha256.txt").write_text(manifest, encoding="utf-8")
    return 0 if passed else 1


class NormalPairTests(unittest.TestCase):
    def test_both_frozen_versions_pass_same_normal_controls(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "evidence"
            rc = run_pair(out)
            errors = "\n".join(p.read_text(encoding="utf-8") for p in out.glob("*/worker.stderr"))
            self.assertEqual(rc, 0, errors)

    def test_missing_consumption_fact_is_not_success(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "evidence"
            self.assertEqual(run_pair(out, missing_fact=True), 1)
            for label in VERSIONS:
                self.assertIn("missing exact consumption fact", (out / label / "worker.stderr").read_text(encoding="utf-8"))

    def test_archive_refuses_existing_directory(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(FileExistsError):
                run_pair(Path(tmp))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--worker", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--evidence-dir", type=Path)
    parser.add_argument("--missing-fact", action="store_true")
    args = parser.parse_args()
    if args.worker:
        try:
            run_worker(args.worker.resolve(), args.output.resolve(), args.missing_fact)
            return 0
        except Exception:
            traceback.print_exc()
            return 1
    if not args.evidence_dir:
        parser.error("--evidence-dir required (new directory, never overwritten)")
    return run_pair(args.evidence_dir.resolve(), missing_fact=args.missing_fact)


if __name__ == "__main__":
    sys.exit(main())
